---
title: "Assay distributions"
author: "Kara Tsang, Kat Holt"
date: "Last compiled on `r format(Sys.time(), '%d/%m/%y')`"
output: 
  html_document: 
    df_print: paged
    fig_width: 9
    fig_height: 8
    mode: selfcontained
    highlight: pygments
    theme: 
      bootswatch: flatly
      code_font:
        google: "JetBrains Mono"
editor_options: 
  chunk_output_type: inline
---

```{=html}
<style type="text/css">
.main-container {
  max-width: 1600px !important;
  margin-left: auto;
  margin-right: auto;
}
</style>
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = 'png', echo = TRUE, message = FALSE, warning = FALSE,
                      cache = FALSE, fig.align = 'center')
knitr::opts_knit$set(root.dir = getwd())

# Data wrangling
library(tidyverse)
library(dplyr)
```

# load data
``` {r}
geno <- read_delim("tables/TableS2_genotypes.tsv")
pheno <- read_delim("tables/TableS3_phenotypes_metadata.tsv")
cipro_antibiogram <- full_join(geno,pheno)

```

## colours
``` {r}

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)
```

# Relabel MIC datasets
```{r}
cipro_antibiogram_MIC <- cipro_antibiogram

cipro_antibiogram_MIC$index[cipro_antibiogram_MIC$index == "KASPAH" ] <- "KASPAH (V=1172)"
cipro_antibiogram_MIC$index[cipro_antibiogram_MIC$index == "KLEBGAP" ] <- "KLEBGAP (V=92, E=4)"
cipro_antibiogram_MIC$index[cipro_antibiogram_MIC$index == "India_GHRU" ] <- "India_GHRU (V=831)"
cipro_antibiogram_MIC$index[cipro_antibiogram_MIC$index == "Leangapichart_2021" ] <- "Leangapichart_2021 (V=38)"
cipro_antibiogram_MIC$index[cipro_antibiogram_MIC$index == "Philippines" ] <- "Philippines (V=227)"
cipro_antibiogram_MIC$index[cipro_antibiogram_MIC$index == "Torok_2020" ] <- "Torok_2020 (V=1296)"
cipro_antibiogram_MIC$index[cipro_antibiogram_MIC$index == "Egli" ] <- "Egli (V=127)"
cipro_antibiogram_MIC$index[cipro_antibiogram_MIC$index == "Long" ] <- "Long (P=1595)"
cipro_antibiogram_MIC$index[cipro_antibiogram_MIC$index == "Denmark_MedVetKlebs" ] <- "Denmark_MedVetKlebs (S=49)"
cipro_antibiogram_MIC$index[cipro_antibiogram_MIC$index == "Mathers" ] <- "Mathers (S=27)"
cipro_antibiogram_MIC$index[cipro_antibiogram_MIC$index == "Italy_MVK_MIC" ] <- "Italy_MVK_MIC (S=85)"
cipro_antibiogram_MIC$index[cipro_antibiogram_MIC$index == "BSAC" ] <- "BSAC (A=247)"
cipro_antibiogram_MIC$index[cipro_antibiogram_MIC$index == "Milan_2019" ] <- "Milan_2019 (S=98)"
cipro_antibiogram_MIC$index[cipro_antibiogram_MIC$index == "Wright" ] <- "Wright (V=80)"
cipro_antibiogram_MIC$index[cipro_antibiogram_MIC$index == "Colombia_GHRU" ] <- "Colombia_GHRU (V=394)"
cipro_antibiogram_MIC$index[cipro_antibiogram_MIC$index == "BARNARDS" ] <- "BARNARDS (A=251)"
cipro_antibiogram_MIC$index[cipro_antibiogram_MIC$index == "SPARK" ] <- "SPARK (P=1956)"
cipro_antibiogram_MIC$index[cipro_antibiogram_MIC$index == "Ellington" ] <- "Ellington (V=70)"
cipro_antibiogram_MIC$index[cipro_antibiogram_MIC$index == "Nigeria_GHRU" ] <- "Nigeria_GHRU (V=108)"
cipro_antibiogram_MIC$index[cipro_antibiogram_MIC$index == "Stoesser_2013" ] <- "Stoesser_2013 (P=69)"
cipro_antibiogram_MIC$index[cipro_antibiogram_MIC$index == "Heinz_2019" ] <- "Heinz_2019 (V=178)"
cipro_antibiogram_MIC$index[cipro_antibiogram_MIC$index == "Bachman_2022" ] <- "Bachman_2022 (S=85)"



cipro_antibiogram_MIC$index <- factor(cipro_antibiogram_MIC$index, levels = c(
  "Torok_2020 (V=1296)",
  "KASPAH (V=1172)",
  "India_GHRU (V=831)",
  "Colombia_GHRU (V=394)",
  "Philippines (V=227)",
  "Heinz_2019 (V=178)",
  "Egli (V=127)",
  "Nigeria_GHRU (V=108)",
  "KLEBGAP (V=92, E=4)",
  "Wright (V=80)",
  "Ellington (V=70)",
  "Leangapichart_2021 (V=38)",
  "SPARK (P=1956)", 
  "Long (P=1595)",
  "Stoesser_2013 (P=69)",
  "Milan_2019 (S=98)",
  "Bachman_2022 (S=85)",
  "Italy_MVK_MIC (S=85)",
  "Denmark_MedVetKlebs (S=49)",
  "Mathers (S=27)",
  "BARNARDS (A=251)",
  "BSAC (A=247)"
 ))

```


# MIC
``` {r}
MIC_dist <- cipro_antibiogram_MIC %>%
  filter(Laboratory.Typing.Method!="Disk diffusion") %>%
  mutate(Measurement=replace(Measurement, Measurement==0.032, 0.03)) %>%
  mutate(Measurement=replace(Measurement, Measurement==0.064, 0.06)) %>%
  mutate(Measurement=replace(Measurement, Measurement==0.12, 0.125)) %>%
  group_by(Measurement, index) %>% count() %>%
  ggplot(aes(x=factor(Measurement), y=n, fill=index)) + 
  geom_bar(position="stack", stat="identity") +
  theme_bw() +
  labs(x="MIC (mg/L)", y="Number of genomes", fill="Dataset") +
  scale_fill_manual(values=c25[1:22]) +
  geom_vline(xintercept=4.5, linetype=2) +
  annotate("text",x=4.25, y=2900, label="S") +
  geom_vline(xintercept=5.5, linetype=2) +
  annotate("text",x=5.75, y=2900, label="R")

```

# Figure S2 - MIC distribution
``` {r figs2}

MIC_dist

ggsave(width=9, height=4, file="figs/FigS2_MIC_distribution.pdf")
ggsave(width=9, height=4, file="figs/FigS2_MIC_distribution.png")

```

# Relabel DD datasets
```{r}
cipro_antibiogram_DD <- cipro_antibiogram

cipro_antibiogram_DD$index[cipro_antibiogram_DD$index == "Huynh_2020" ] <- "Huynh_2020 (N=262)"
cipro_antibiogram_DD$index[cipro_antibiogram_DD$index == "KLEBGAP" ] <- "KLEBGAP (N=2379)"
cipro_antibiogram_DD$index[cipro_antibiogram_DD$index == "Philippines_DD" ] <- "Philippines_DD (N=28)"
cipro_antibiogram_DD$index[cipro_antibiogram_DD$index == "Potter_2018" ] <- "Potter_2018 (V=52)"
cipro_antibiogram_DD$index[cipro_antibiogram_DD$index == "perdigao_2022" ] <- "perdigao_2022 (N=334)"
cipro_antibiogram_DD$index[cipro_antibiogram_DD$index == "sands2021_arthropods_DD" ] <- "sands2021_arthropods_DD (N=18)"

cipro_antibiogram_DD$index <- factor(cipro_antibiogram_DD$index, levels = c(
  "KLEBGAP (N=2379)",
  "perdigao_2022 (N=334)",
  "Huynh_2020 (N=262)",
  "Potter_2018 (V=52)",
  "Philippines_DD (N=28)",
  "sands2021_arthropods_DD (N=18)"

 ))

```


# Disk diffusion
``` {r}
DD_dist <- cipro_antibiogram_DD %>%
  filter(Laboratory.Typing.Method=="Disk diffusion") %>%
  group_by(Measurement, index) %>% count() %>%
  ggplot(aes(x=factor(Measurement), y=n, fill=index)) + 
  geom_bar(position="stack", stat="identity") +
  theme_bw() +
  labs(x="Disk diffusion zone diameter (mm)", y="Number of genomes", fill="Dataset") +
  scale_fill_manual(values=c25[10:15]) +
  geom_vline(xintercept=16.5, linetype=2) +
  annotate("text",x=16, y=400, label="R") +
  geom_vline(xintercept=19.5, linetype=2) +
  annotate("text",x=20, y=400, label="S") + 
  scale_x_discrete(breaks=seq(5,45,5))

```

# Figure S3 - DD distribution
``` {r figs3}

DD_dist

ggsave(width=9, height=4, file="figs/FigS3_DD_distribution.pdf")
ggsave(width=9, height=4, file="figs/FigS3_DD_distribution.png")

```
