---
title: "Validation"
author: "Kara Tsang, Kat Holt"
date: "Last compiled on `r format(Sys.time(), '%d/%m/%y')`"
output: 
  html_document: 
    df_print: paged
    fig_width: 9
    fig_height: 8
    mode: selfcontained
    highlight: pygments
    theme: 
      bootswatch: flatly
      code_font:
        google: "JetBrains Mono"
editor_options: 
  chunk_output_type: inline
---

```{=html}
<style type="text/css">
.main-container {
  max-width: 1600px !important;
  margin-left: auto;
  margin-right: auto;
}
</style>
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = 'png', echo = TRUE, message = FALSE, warning = FALSE,
                      cache = FALSE, fig.align = 'center')
knitr::opts_knit$set(root.dir = getwd())

# Data wrangling
library(tidyverse)
library(dplyr)
library(janitor)
library(png)
library(patchwork)
```

# load data
``` {r load_data}
MBIRA_Kpn <- read_delim("MBIRA_ValidationOutput/Prediction_Pheno_summary_Kpn.csv")
MBIRA_Kvv <- read_delim("MBIRA_ValidationOutput/Prediction_Pheno_summary_Kvv.csv")
HowdenGorrie <- read_delim("HowdenGorrie_ValidationOutput/Prediction_Pheno_summary.csv")
AGAR <- read_delim("AGAR_ValidationOutput/Prediction_Pheno_summary.csv")
Milan <- read_delim("MilanSanRafaelle_ValidationOutput/Prediction_Pheno_summary.csv")
HailuEthiopia <- read_delim("HailuEthiopia_ValidationOutput/Prediction_Pheno_summary.csv")
FeaseyMalawi <- read_delim("FeaseyMalawi_ValidationOutput/Prediction_Pheno_summary.csv")
KayamaJapan <- read_delim("KayamaJapan_ValidationOutput/Prediction_Pheno_summary.csv")
EUSCAPE_EURECA <- read_delim("EURECA_EUSCAPE_ValidationOutput/Prediction_Pheno_summary.csv")
EgliSwitzerland <- read_delim("EgliSwitzerland_2025_ValidationOutput/Prediction_Pheno_summary.csv")
HRYC_Spain <- read_delim("HRYC_Spain_ValidationOutput/Prediction_Pheno_summary.csv")
IndiaGHRU <- read_delim("IndiaGHRU_2025_ValidationOutput/Prediction_Pheno_summary.csv")
NeumannGermany <- read_delim("NeumannGermany_ValidationOutput/Prediction_Pheno_summary.csv")
Whitelaw_CHAMPS <- read_delim("Whitelaw_Stellenbosch_ValidationOutput/Prediction_Pheno_summary_DD.csv")
Oxfordshire_Kpn <- read_delim("Oxfordshire_ValidationOutput/Prediction_Pheno_summary_Kpn.csv")
Oxfordshire_Kvv <- read_delim("Oxfordshire_ValidationOutput/Prediction_Pheno_summary_Kvv.csv")
IZSAM_Italy <- read_delim("IZSAM_Italy_ValidationOutput/Prediction_Pheno_summary.csv")
LaPaz_Lazaro <- read_delim("LaPaz_Lazaro_ValidationOutput/Prediction_Pheno_summary.csv")

```

## set colours
``` {r set_colours}
wt_colours <- c(`non-wt (I/R)`="IndianRed", `wt (S)`= "LightBlue")
res_colours <- c("I"="grey", "R"="IndianRed", "S"="LightBlue", "NWT"="grey")
res_colours2 <- c("I"="black", "R"="IndianRed", "S"="LightBlue", "NWT"="black")
res_colours3 <- c("NWT I"="#78638a", "NWT R"="IndianRed", "WT S"="LightBlue")
```

``` {r}
# position dodge for coefficient plots
pd <- position_dodge(width=0.8)
```


## functions to calculate PPV and categorical agreement from models
``` {r model_performance_functions}

cat_agree <- function(xtabs) {
  return((xtabs[1,1]+xtabs[2,2])/sum(xtabs))
}

ppv <- function(xtabs) {
  return(xtabs[2,2]/sum(xtabs[2,]))
}

npv <- function(xtabs) {
  return(xtabs[1,1]/sum(xtabs[1,]))
}

#sens <- function(pred,truth) {
#  xtabs <- table(pred,truth)
#  return(xtabs[2,2]/(sum(xtabs[,2])))
#}

sens <- function(xtabs) {
  return(xtabs[2,2]/(sum(xtabs[,2])))
}

spec <- function(xtabs) {
  return(xtabs[1,1]/(sum(xtabs[,1])))
}

me <- function(xtabs) {
  return(xtabs[2,1]/sum(xtabs[,1]))
}

vme <- function(xtabs) {
  return(xtabs[1,2]/sum(xtabs[,2]))
}

perc_R <- function(xtabs) {
  return(sum(xtabs[,2])/sum(xtabs))
}


metrics <- function(xtabs) {
  return(list(cat=cat_agree(xtabs),
              ppv=ppv(xtabs),
              npv=npv(xtabs),
              sens=sens(xtabs),
              spec=spec(xtabs),
              me=me(xtabs),
              vme=vme(xtabs),
              perc_R=perc_R(xtabs),
              n=sum(xtabs),
              summary=c("cat"=cat_agree(xtabs),
                    "sens"=sens(xtabs),
                    "spec"=spec(xtabs),
                    "me"=me(xtabs),
                    "vme"=vme(xtabs),
                    "perc_R"=perc_R(xtabs),
                    "n"=sum(xtabs)
              )
          )
    )
}

``` 


# data wrangling 
```{r MBIRA_Kpn}

MBIRA_Kpn_SI <- MBIRA_Kpn %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_S" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_S_I", Group)) 

MBIRA_Kpn_R <- MBIRA_Kpn %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_R" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_I_R", Group)) 

MBIRA_Kpn_SIR <- rbind(MBIRA_Kpn_SI, MBIRA_Kpn_R) %>% distinct()

subset(MBIRA_Kpn_SIR, Group == "pred_S_I")$S_I
table(MBIRA_Kpn_SIR$S_I)

MBIRA_Kpn_R_prediction <- matrix(c(subset(MBIRA_Kpn_SIR, Group == "pred_S_I")$S_I, 
                subset(MBIRA_Kpn_SIR, Group == "pred_S_I")$R,
                subset(MBIRA_Kpn_SIR, Group == "pred_R")$S_I,
                subset(MBIRA_Kpn_SIR, Group == "pred_R")$R), ncol=2, byrow=TRUE)

colnames(MBIRA_Kpn_R_prediction) <- c('S_I','R')
rownames(MBIRA_Kpn_R_prediction) <- c('pred_S_I','pred_R')
MBIRA_Kpn_R_prediction_summary<-metrics(MBIRA_Kpn_R_prediction)

MBIRA_Kpn_NWT_prediction <- matrix(c(subset(MBIRA_Kpn_SIR, Group == "pred_S")$S, 
                subset(MBIRA_Kpn_SIR, Group == "pred_S")$I_R,
                subset(MBIRA_Kpn_SIR, Group == "pred_I_R")$S,
                subset(MBIRA_Kpn_SIR, Group == "pred_I_R")$I_R), ncol=2, byrow=TRUE)
colnames(MBIRA_Kpn_NWT_prediction) <- c('S','I_R')
rownames(MBIRA_Kpn_NWT_prediction) <- c('pred_S','pred_I_R')
MBIRA_Kpn_NWT_prediction_summary<-metrics(MBIRA_Kpn_NWT_prediction)
```

```{r MBIRA_Kvv}

MBIRA_Kvv_SI <- MBIRA_Kvv %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_S" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_S_I", Group)) 

MBIRA_Kvv_R <- MBIRA_Kvv %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_R" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_I_R", Group)) 

MBIRA_Kvv_SIR <- rbind(MBIRA_Kvv_SI, MBIRA_Kvv_R) %>% distinct()

subset(MBIRA_Kvv_SIR, Group == "pred_S_I")$S_I
table(MBIRA_Kvv_SIR$S_I)

MBIRA_Kvv_R_prediction <- matrix(c(subset(MBIRA_Kvv_SIR, Group == "pred_S_I")$S_I, 
                subset(MBIRA_Kvv_SIR, Group == "pred_S_I")$R,
                subset(MBIRA_Kvv_SIR, Group == "pred_R")$S_I,
                subset(MBIRA_Kvv_SIR, Group == "pred_R")$R), ncol=2, byrow=TRUE)

colnames(MBIRA_Kvv_R_prediction) <- c('S_I','R')
rownames(MBIRA_Kvv_R_prediction) <- c('pred_S_I','pred_R')
MBIRA_Kvv_R_prediction_summary<-metrics(MBIRA_Kvv_R_prediction)

MBIRA_Kvv_NWT_prediction <- matrix(c(subset(MBIRA_Kvv_SIR, Group == "pred_S")$S, 
                subset(MBIRA_Kvv_SIR, Group == "pred_S")$I_R,
                subset(MBIRA_Kvv_SIR, Group == "pred_I_R")$S,
                subset(MBIRA_Kvv_SIR, Group == "pred_I_R")$I_R), ncol=2, byrow=TRUE)
colnames(MBIRA_Kvv_NWT_prediction) <- c('S','I_R')
rownames(MBIRA_Kvv_NWT_prediction) <- c('pred_S','pred_I_R')
MBIRA_Kvv_NWT_prediction_summary<-metrics(MBIRA_Kvv_NWT_prediction)
```

```{r HowdenGorrie}

HowdenGorrie_SI <- HowdenGorrie %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_S" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_S_I", Group)) 

HowdenGorrie_R <- HowdenGorrie %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_R" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_I_R", Group)) 

HowdenGorrie_SIR <- rbind(HowdenGorrie_SI, HowdenGorrie_R) %>% distinct()

subset(HowdenGorrie_SIR, Group == "pred_S_I")$S_I
table(HowdenGorrie_SIR$S_I)

HowdenGorrie_R_prediction <- matrix(c(subset(HowdenGorrie_SIR, Group == "pred_S_I")$S_I, 
                subset(HowdenGorrie_SIR, Group == "pred_S_I")$R,
                subset(HowdenGorrie_SIR, Group == "pred_R")$S_I,
                subset(HowdenGorrie_SIR, Group == "pred_R")$R), ncol=2, byrow=TRUE)

colnames(HowdenGorrie_R_prediction) <- c('S_I','R')
rownames(HowdenGorrie_R_prediction) <- c('pred_S_I','pred_R')
HowdenGorrie_R_prediction_summary<-metrics(HowdenGorrie_R_prediction)

HowdenGorrie_NWT_prediction <- matrix(c(subset(HowdenGorrie_SIR, Group == "pred_S")$S, 
                subset(HowdenGorrie_SIR, Group == "pred_S")$I_R,
                subset(HowdenGorrie_SIR, Group == "pred_I_R")$S,
                subset(HowdenGorrie_SIR, Group == "pred_I_R")$I_R), ncol=2, byrow=TRUE)
colnames(HowdenGorrie_NWT_prediction) <- c('S','I_R')
rownames(HowdenGorrie_NWT_prediction) <- c('pred_S','pred_I_R')
HowdenGorrie_NWT_prediction_summary<-metrics(HowdenGorrie_NWT_prediction)
```

```{r AGAR}

AGAR_SI <- AGAR %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_S" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_S_I", Group)) 


AGAR_R <- AGAR %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_R" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_I_R", Group)) 

AGAR_SIR <- rbind(AGAR_SI, AGAR_R) %>% distinct()

subset(AGAR_SIR, Group == "pred_S_I")$S_I
table(AGAR_SIR$S_I)

AGAR_R_prediction <- matrix(c(subset(AGAR_SIR, Group == "pred_S_I")$S_I, 
                subset(AGAR_SIR, Group == "pred_S_I")$R,
                subset(AGAR_SIR, Group == "pred_R")$S_I,
                subset(AGAR_SIR, Group == "pred_R")$R), ncol=2, byrow=TRUE)

colnames(AGAR_R_prediction) <- c('S_I','R')
rownames(AGAR_R_prediction) <- c('pred_S_I','pred_R')
AGAR_R_prediction_summary<-metrics(AGAR_R_prediction)

AGAR_NWT_prediction <- matrix(c(subset(AGAR_SIR, Group == "pred_S")$S, 
                subset(AGAR_SIR, Group == "pred_S")$I_R,
                subset(AGAR_SIR, Group == "pred_I_R")$S,
                subset(AGAR_SIR, Group == "pred_I_R")$I_R), ncol=2, byrow=TRUE)
colnames(AGAR_NWT_prediction) <- c('S','I_R')
rownames(AGAR_NWT_prediction) <- c('pred_S','pred_I_R')
AGAR_NWT_prediction_summary<-metrics(AGAR_NWT_prediction)
```

```{r Milan}

Milan_SI <- Milan %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_S" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_S_I", Group)) 


Milan_R <- Milan %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_R" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_I_R", Group)) 

Milan_SIR <- rbind(Milan_SI, Milan_R) %>% distinct()

subset(Milan_SIR, Group == "pred_S_I")$S_I
table(Milan_SIR$S_I)

Milan_R_prediction <- matrix(c(subset(Milan_SIR, Group == "pred_S_I")$S_I, 
                subset(Milan_SIR, Group == "pred_S_I")$R,
                subset(Milan_SIR, Group == "pred_R")$S_I,
                subset(Milan_SIR, Group == "pred_R")$R), ncol=2, byrow=TRUE)

colnames(Milan_R_prediction) <- c('S_I','R')
rownames(Milan_R_prediction) <- c('pred_S_I','pred_R')
Milan_R_prediction_summary<-metrics(Milan_R_prediction)

Milan_NWT_prediction <- matrix(c(subset(Milan_SIR, Group == "pred_S")$S, 
                subset(Milan_SIR, Group == "pred_S")$I_R,
                subset(Milan_SIR, Group == "pred_I_R")$S,
                subset(Milan_SIR, Group == "pred_I_R")$I_R), ncol=2, byrow=TRUE)
colnames(Milan_NWT_prediction) <- c('S','I_R')
rownames(Milan_NWT_prediction) <- c('pred_S','pred_I_R')
Milan_NWT_prediction_summary<-metrics(Milan_NWT_prediction)
```


```{r HailuEthiopia}

HailuEthiopia_SI <- HailuEthiopia %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_S" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_S_I", Group)) 


HailuEthiopia_R <- HailuEthiopia %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_R" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_I_R", Group)) 

HailuEthiopia_SIR <- rbind(HailuEthiopia_SI, HailuEthiopia_R) %>% distinct()

subset(HailuEthiopia_SIR, Group == "pred_S_I")$S_I
table(HailuEthiopia_SIR$S_I)

HailuEthiopia_R_prediction <- matrix(c(subset(HailuEthiopia_SIR, Group == "pred_S_I")$S_I, 
                subset(HailuEthiopia_SIR, Group == "pred_S_I")$R,
                subset(HailuEthiopia_SIR, Group == "pred_R")$S_I,
                subset(HailuEthiopia_SIR, Group == "pred_R")$R), ncol=2, byrow=TRUE)

colnames(HailuEthiopia_R_prediction) <- c('S_I','R')
rownames(HailuEthiopia_R_prediction) <- c('pred_S_I','pred_R')
HailuEthiopia_R_prediction_summary<-metrics(HailuEthiopia_R_prediction)

HailuEthiopia_NWT_prediction <- matrix(c(subset(HailuEthiopia_SIR, Group == "pred_S")$S, 
                subset(HailuEthiopia_SIR, Group == "pred_S")$I_R,
                subset(HailuEthiopia_SIR, Group == "pred_I_R")$S,
                subset(HailuEthiopia_SIR, Group == "pred_I_R")$I_R), ncol=2, byrow=TRUE)
colnames(HailuEthiopia_NWT_prediction) <- c('S','I_R')
rownames(HailuEthiopia_NWT_prediction) <- c('pred_S','pred_I_R')
HailuEthiopia_NWT_prediction_summary<-metrics(HailuEthiopia_NWT_prediction)
```


```{r KayamaJapan}

KayamaJapan_SI <- KayamaJapan %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_S" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_S_I", Group)) 


KayamaJapan_R <- KayamaJapan %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_R" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_I_R", Group)) 

KayamaJapan_SIR <- rbind(KayamaJapan_SI, KayamaJapan_R) %>% distinct()

subset(KayamaJapan_SIR, Group == "pred_S_I")$S_I
table(KayamaJapan_SIR$S_I)

KayamaJapan_R_prediction <- matrix(c(subset(KayamaJapan_SIR, Group == "pred_S_I")$S_I, 
                subset(KayamaJapan_SIR, Group == "pred_S_I")$R,
                subset(KayamaJapan_SIR, Group == "pred_R")$S_I,
                subset(KayamaJapan_SIR, Group == "pred_R")$R), ncol=2, byrow=TRUE)

colnames(KayamaJapan_R_prediction) <- c('S_I','R')
rownames(KayamaJapan_R_prediction) <- c('pred_S_I','pred_R')
KayamaJapan_R_prediction_summary<-metrics(KayamaJapan_R_prediction)

KayamaJapan_NWT_prediction <- matrix(c(subset(KayamaJapan_SIR, Group == "pred_S")$S, 
                subset(KayamaJapan_SIR, Group == "pred_S")$I_R,
                subset(KayamaJapan_SIR, Group == "pred_I_R")$S,
                subset(KayamaJapan_SIR, Group == "pred_I_R")$I_R), ncol=2, byrow=TRUE)
colnames(KayamaJapan_NWT_prediction) <- c('S','I_R')
rownames(KayamaJapan_NWT_prediction) <- c('pred_S','pred_I_R')
KayamaJapan_NWT_prediction_summary<-metrics(KayamaJapan_NWT_prediction)
```


```{r FeaseyMalawi}

FeaseyMalawi_SI <- FeaseyMalawi %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_S" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_S_I", Group)) 


FeaseyMalawi_R <- FeaseyMalawi %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_R" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_I_R", Group)) 

FeaseyMalawi_SIR <- rbind(FeaseyMalawi_SI, FeaseyMalawi_R) %>% distinct()

subset(FeaseyMalawi_SIR, Group == "pred_S_I")$S_I
table(FeaseyMalawi_SIR$S_I)

FeaseyMalawi_R_prediction <- matrix(c(subset(FeaseyMalawi_SIR, Group == "pred_S_I")$S_I, 
                subset(FeaseyMalawi_SIR, Group == "pred_S_I")$R,
                subset(FeaseyMalawi_SIR, Group == "pred_R")$S_I,
                subset(FeaseyMalawi_SIR, Group == "pred_R")$R), ncol=2, byrow=TRUE)

colnames(FeaseyMalawi_R_prediction) <- c('S_I','R')
rownames(FeaseyMalawi_R_prediction) <- c('pred_S_I','pred_R')
FeaseyMalawi_R_prediction_summary<-metrics(FeaseyMalawi_R_prediction)

FeaseyMalawi_NWT_prediction <- matrix(c(subset(FeaseyMalawi_SIR, Group == "pred_S")$S, 
                subset(FeaseyMalawi_SIR, Group == "pred_S")$I_R,
                subset(FeaseyMalawi_SIR, Group == "pred_I_R")$S,
                subset(FeaseyMalawi_SIR, Group == "pred_I_R")$I_R), ncol=2, byrow=TRUE)
colnames(FeaseyMalawi_NWT_prediction) <- c('S','I_R')
rownames(FeaseyMalawi_NWT_prediction) <- c('pred_S','pred_I_R')
FeaseyMalawi_NWT_prediction_summary<-metrics(FeaseyMalawi_NWT_prediction)
```

```{r EUSCAPE_EURECA}

EUSCAPE_EURECA_SI <- EUSCAPE_EURECA %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_S" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_S_I", Group)) 


EUSCAPE_EURECA_R <- EUSCAPE_EURECA %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_R" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_I_R", Group)) 

EUSCAPE_EURECA_SIR <- rbind(EUSCAPE_EURECA_SI, EUSCAPE_EURECA_R) %>% distinct()

subset(EUSCAPE_EURECA_SIR, Group == "pred_S_I")$S_I
table(EUSCAPE_EURECA_SIR$S_I)

EUSCAPE_EURECA_R_prediction <- matrix(c(subset(EUSCAPE_EURECA_SIR, Group == "pred_S_I")$S_I, 
                subset(EUSCAPE_EURECA_SIR, Group == "pred_S_I")$R,
                subset(EUSCAPE_EURECA_SIR, Group == "pred_R")$S_I,
                subset(EUSCAPE_EURECA_SIR, Group == "pred_R")$R), ncol=2, byrow=TRUE)

colnames(EUSCAPE_EURECA_R_prediction) <- c('S_I','R')
rownames(EUSCAPE_EURECA_R_prediction) <- c('pred_S_I','pred_R')
EUSCAPE_EURECA_R_prediction_summary<-metrics(EUSCAPE_EURECA_R_prediction)

EUSCAPE_EURECA_NWT_prediction <- matrix(c(subset(EUSCAPE_EURECA_SIR, Group == "pred_S")$S, 
                subset(EUSCAPE_EURECA_SIR, Group == "pred_S")$I_R,
                subset(EUSCAPE_EURECA_SIR, Group == "pred_I_R")$S,
                subset(EUSCAPE_EURECA_SIR, Group == "pred_I_R")$I_R), ncol=2, byrow=TRUE)
colnames(EUSCAPE_EURECA_NWT_prediction) <- c('S','I_R')
rownames(EUSCAPE_EURECA_NWT_prediction) <- c('pred_S','pred_I_R')
EUSCAPE_EURECA_NWT_prediction_summary<-metrics(EUSCAPE_EURECA_NWT_prediction)
```

```{r EgliSwitzerland}

EgliSwitzerland_SI <- EgliSwitzerland %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_S" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_S_I", Group)) 


EgliSwitzerland_R <- EgliSwitzerland %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_R" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_I_R", Group)) 

EgliSwitzerland_SIR <- rbind(EgliSwitzerland_SI, EgliSwitzerland_R) %>% distinct()

subset(EgliSwitzerland_SIR, Group == "pred_S_I")$S_I
table(EgliSwitzerland_SIR$S_I)

EgliSwitzerland_R_prediction <- matrix(c(subset(EgliSwitzerland_SIR, Group == "pred_S_I")$S_I, 
                subset(EgliSwitzerland_SIR, Group == "pred_S_I")$R,
                subset(EgliSwitzerland_SIR, Group == "pred_R")$S_I,
                subset(EgliSwitzerland_SIR, Group == "pred_R")$R), ncol=2, byrow=TRUE)

colnames(EgliSwitzerland_R_prediction) <- c('S_I','R')
rownames(EgliSwitzerland_R_prediction) <- c('pred_S_I','pred_R')
EgliSwitzerland_R_prediction_summary<-metrics(EgliSwitzerland_R_prediction)

EgliSwitzerland_NWT_prediction <- matrix(c(subset(EgliSwitzerland_SIR, Group == "pred_S")$S, 
                subset(EgliSwitzerland_SIR, Group == "pred_S")$I_R,
                subset(EgliSwitzerland_SIR, Group == "pred_I_R")$S,
                subset(EgliSwitzerland_SIR, Group == "pred_I_R")$I_R), ncol=2, byrow=TRUE)
colnames(EgliSwitzerland_NWT_prediction) <- c('S','I_R')
rownames(EgliSwitzerland_NWT_prediction) <- c('pred_S','pred_I_R')
EgliSwitzerland_NWT_prediction_summary<-metrics(EgliSwitzerland_NWT_prediction)
```

```{r HRYC_Spain}

HRYC_Spain_SI <- HRYC_Spain %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_S" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_S_I", Group)) 


HRYC_Spain_R <- HRYC_Spain %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_R" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_I_R", Group)) 

HRYC_Spain_SIR <- rbind(HRYC_Spain_SI, HRYC_Spain_R) %>% distinct()

subset(HRYC_Spain_SIR, Group == "pred_S_I")$S_I
table(HRYC_Spain_SIR$S_I)

HRYC_Spain_R_prediction <- matrix(c(subset(HRYC_Spain_SIR, Group == "pred_S_I")$S_I, 
                subset(HRYC_Spain_SIR, Group == "pred_S_I")$R,
                subset(HRYC_Spain_SIR, Group == "pred_R")$S_I,
                subset(HRYC_Spain_SIR, Group == "pred_R")$R), ncol=2, byrow=TRUE)

colnames(HRYC_Spain_R_prediction) <- c('S_I','R')
rownames(HRYC_Spain_R_prediction) <- c('pred_S_I','pred_R')
HRYC_Spain_R_prediction_summary<-metrics(HRYC_Spain_R_prediction)

HRYC_Spain_NWT_prediction <- matrix(c(subset(HRYC_Spain_SIR, Group == "pred_S")$S, 
                subset(HRYC_Spain_SIR, Group == "pred_S")$I_R,
                subset(HRYC_Spain_SIR, Group == "pred_I_R")$S,
                subset(HRYC_Spain_SIR, Group == "pred_I_R")$I_R), ncol=2, byrow=TRUE)
colnames(HRYC_Spain_NWT_prediction) <- c('S','I_R')
rownames(HRYC_Spain_NWT_prediction) <- c('pred_S','pred_I_R')
HRYC_Spain_NWT_prediction_summary<-metrics(HRYC_Spain_NWT_prediction)
```


```{r IndiaGHRU}

IndiaGHRU_SI <- IndiaGHRU %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_S" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_S_I", Group)) 


IndiaGHRU_R <- IndiaGHRU %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_R" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_I_R", Group)) 

IndiaGHRU_SIR <- rbind(IndiaGHRU_SI, IndiaGHRU_R) %>% distinct()

subset(IndiaGHRU_SIR, Group == "pred_S_I")$S_I
table(IndiaGHRU_SIR$S_I)

IndiaGHRU_R_prediction <- matrix(c(subset(IndiaGHRU_SIR, Group == "pred_S_I")$S_I, 
                subset(IndiaGHRU_SIR, Group == "pred_S_I")$R,
                subset(IndiaGHRU_SIR, Group == "pred_R")$S_I,
                subset(IndiaGHRU_SIR, Group == "pred_R")$R), ncol=2, byrow=TRUE)

colnames(IndiaGHRU_R_prediction) <- c('S_I','R')
rownames(IndiaGHRU_R_prediction) <- c('pred_S_I','pred_R')
IndiaGHRU_R_prediction_summary<-metrics(IndiaGHRU_R_prediction)

IndiaGHRU_NWT_prediction <- matrix(c(subset(IndiaGHRU_SIR, Group == "pred_S")$S, 
                subset(IndiaGHRU_SIR, Group == "pred_S")$I_R,
                subset(IndiaGHRU_SIR, Group == "pred_I_R")$S,
                subset(IndiaGHRU_SIR, Group == "pred_I_R")$I_R), ncol=2, byrow=TRUE)
colnames(IndiaGHRU_NWT_prediction) <- c('S','I_R')
rownames(IndiaGHRU_NWT_prediction) <- c('pred_S','pred_I_R')
IndiaGHRU_NWT_prediction_summary<-metrics(IndiaGHRU_NWT_prediction)
```

```{r NeumannGermany}

NeumannGermany_SI <- NeumannGermany %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_S" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_S_I", Group)) 


NeumannGermany_R <- NeumannGermany %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_R" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_I_R", Group)) 

NeumannGermany_SIR <- rbind(NeumannGermany_SI, NeumannGermany_R) %>% distinct()

subset(NeumannGermany_SIR, Group == "pred_S_I")$S_I
table(NeumannGermany_SIR$S_I)

NeumannGermany_R_prediction <- matrix(c(subset(NeumannGermany_SIR, Group == "pred_S_I")$S_I, 
                subset(NeumannGermany_SIR, Group == "pred_S_I")$R,
                subset(NeumannGermany_SIR, Group == "pred_R")$S_I,
                subset(NeumannGermany_SIR, Group == "pred_R")$R), ncol=2, byrow=TRUE)

colnames(NeumannGermany_R_prediction) <- c('S_I','R')
rownames(NeumannGermany_R_prediction) <- c('pred_S_I','pred_R')
NeumannGermany_R_prediction_summary<-metrics(NeumannGermany_R_prediction)

NeumannGermany_NWT_prediction <- matrix(c(subset(NeumannGermany_SIR, Group == "pred_S")$S, 
                subset(NeumannGermany_SIR, Group == "pred_S")$I_R,
                subset(NeumannGermany_SIR, Group == "pred_I_R")$S,
                subset(NeumannGermany_SIR, Group == "pred_I_R")$I_R), ncol=2, byrow=TRUE)
colnames(NeumannGermany_NWT_prediction) <- c('S','I_R')
rownames(NeumannGermany_NWT_prediction) <- c('pred_S','pred_I_R')
NeumannGermany_NWT_prediction_summary<-metrics(NeumannGermany_NWT_prediction)
```


```{r Whitelaw_CHAMPS}

Whitelaw_CHAMPS_SI <- Whitelaw_CHAMPS %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_S" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_S_I", Group)) 

Whitelaw_CHAMPS_R <- Whitelaw_CHAMPS %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_R" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_I_R", Group)) 

Whitelaw_CHAMPS_SIR <- rbind(Whitelaw_CHAMPS_SI, Whitelaw_CHAMPS_R) %>% distinct()

subset(Whitelaw_CHAMPS_SIR, Group == "pred_S_I")$S_I
table(Whitelaw_CHAMPS_SIR$S_I)

Whitelaw_CHAMPS_R_prediction <- matrix(c(subset(Whitelaw_CHAMPS_SIR, Group == "pred_S_I")$S_I, 
                subset(Whitelaw_CHAMPS_SIR, Group == "pred_S_I")$R,
                subset(Whitelaw_CHAMPS_SIR, Group == "pred_R")$S_I,
                subset(Whitelaw_CHAMPS_SIR, Group == "pred_R")$R), ncol=2, byrow=TRUE)

colnames(Whitelaw_CHAMPS_R_prediction) <- c('S_I','R')
rownames(Whitelaw_CHAMPS_R_prediction) <- c('pred_S_I','pred_R')
Whitelaw_CHAMPS_R_prediction_summary<-metrics(Whitelaw_CHAMPS_R_prediction)

Whitelaw_CHAMPS_NWT_prediction <- matrix(c(subset(Whitelaw_CHAMPS_SIR, Group == "pred_S")$S, 
                subset(Whitelaw_CHAMPS_SIR, Group == "pred_S")$I_R,
                subset(Whitelaw_CHAMPS_SIR, Group == "pred_I_R")$S,
                subset(Whitelaw_CHAMPS_SIR, Group == "pred_I_R")$I_R), ncol=2, byrow=TRUE)
colnames(Whitelaw_CHAMPS_NWT_prediction) <- c('S','I_R')
rownames(Whitelaw_CHAMPS_NWT_prediction) <- c('pred_S','pred_I_R')
Whitelaw_CHAMPS_NWT_prediction_summary<-metrics(Whitelaw_CHAMPS_NWT_prediction)
```

```{r Oxfordshire_Kpn}

Oxfordshire_Kpn_SI <- Oxfordshire_Kpn %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_S" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_S_I", Group)) 

Oxfordshire_Kpn_R <- Oxfordshire_Kpn %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_R" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_I_R", Group)) 

Oxfordshire_Kpn_SIR <- rbind(Oxfordshire_Kpn_SI, Oxfordshire_Kpn_R) %>% distinct()

subset(Oxfordshire_Kpn_SIR, Group == "pred_S_I")$S_I
table(Oxfordshire_Kpn_SIR$S_I)

Oxfordshire_Kpn_R_prediction <- matrix(c(subset(Oxfordshire_Kpn_SIR, Group == "pred_S_I")$S_I, 
                subset(Oxfordshire_Kpn_SIR, Group == "pred_S_I")$R,
                subset(Oxfordshire_Kpn_SIR, Group == "pred_R")$S_I,
                subset(Oxfordshire_Kpn_SIR, Group == "pred_R")$R), ncol=2, byrow=TRUE)

colnames(Oxfordshire_Kpn_R_prediction) <- c('S_I','R')
rownames(Oxfordshire_Kpn_R_prediction) <- c('pred_S_I','pred_R')
Oxfordshire_Kpn_R_prediction_summary<-metrics(Oxfordshire_Kpn_R_prediction)

Oxfordshire_Kpn_NWT_prediction <- matrix(c(subset(Oxfordshire_Kpn_SIR, Group == "pred_S")$S, 
                subset(Oxfordshire_Kpn_SIR, Group == "pred_S")$I_R,
                subset(Oxfordshire_Kpn_SIR, Group == "pred_I_R")$S,
                subset(Oxfordshire_Kpn_SIR, Group == "pred_I_R")$I_R), ncol=2, byrow=TRUE)
colnames(Oxfordshire_Kpn_NWT_prediction) <- c('S','I_R')
rownames(Oxfordshire_Kpn_NWT_prediction) <- c('pred_S','pred_I_R')
Oxfordshire_Kpn_NWT_prediction_summary<-metrics(Oxfordshire_Kpn_NWT_prediction)
```

```{r Oxfordshire_Kvv}

Oxfordshire_Kvv_SI <- Oxfordshire_Kvv %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_S" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_S_I", Group)) 

Oxfordshire_Kvv_R <- Oxfordshire_Kvv %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_R" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_I_R", Group)) 

Oxfordshire_Kvv_SIR <- rbind(Oxfordshire_Kvv_SI, Oxfordshire_Kvv_R) %>% distinct()

subset(Oxfordshire_Kvv_SIR, Group == "pred_S_I")$S_I
table(Oxfordshire_Kvv_SIR$S_I)

Oxfordshire_Kvv_R_prediction <- matrix(c(subset(Oxfordshire_Kvv_SIR, Group == "pred_S_I")$S_I, 
                subset(Oxfordshire_Kvv_SIR, Group == "pred_S_I")$R,
                subset(Oxfordshire_Kvv_SIR, Group == "pred_R")$S_I,
                subset(Oxfordshire_Kvv_SIR, Group == "pred_R")$R), ncol=2, byrow=TRUE)

colnames(Oxfordshire_Kvv_R_prediction) <- c('S_I','R')
rownames(Oxfordshire_Kvv_R_prediction) <- c('pred_S_I','pred_R')
Oxfordshire_Kvv_R_prediction_summary<-metrics(Oxfordshire_Kvv_R_prediction)

Oxfordshire_Kvv_NWT_prediction <- matrix(c(subset(Oxfordshire_Kvv_SIR, Group == "pred_S")$S, 
                subset(Oxfordshire_Kvv_SIR, Group == "pred_S")$I_R,
                subset(Oxfordshire_Kvv_SIR, Group == "pred_I_R")$S,
                subset(Oxfordshire_Kvv_SIR, Group == "pred_I_R")$I_R), ncol=2, byrow=TRUE)
colnames(Oxfordshire_Kvv_NWT_prediction) <- c('S','I_R')
rownames(Oxfordshire_Kvv_NWT_prediction) <- c('pred_S','pred_I_R')
Oxfordshire_Kvv_NWT_prediction_summary<-metrics(Oxfordshire_Kvv_NWT_prediction)
```
```{r IZSAM_Italy}

IZSAM_Italy_SI <- IZSAM_Italy %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_S" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_S_I", Group)) 

IZSAM_Italy_R <- IZSAM_Italy %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_R" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_I_R", Group)) 

IZSAM_Italy_SIR <- rbind(IZSAM_Italy_SI, IZSAM_Italy_R) %>% distinct()

subset(IZSAM_Italy_SIR, Group == "pred_S_I")$S_I
table(IZSAM_Italy_SIR$S_I)

IZSAM_Italy_R_prediction <- matrix(c(subset(IZSAM_Italy_SIR, Group == "pred_S_I")$S_I, 
                subset(IZSAM_Italy_SIR, Group == "pred_S_I")$R,
                subset(IZSAM_Italy_SIR, Group == "pred_R")$S_I,
                subset(IZSAM_Italy_SIR, Group == "pred_R")$R), ncol=2, byrow=TRUE)

colnames(IZSAM_Italy_R_prediction) <- c('S_I','R')
rownames(IZSAM_Italy_R_prediction) <- c('pred_S_I','pred_R')
IZSAM_Italy_R_prediction_summary<-metrics(IZSAM_Italy_R_prediction)

IZSAM_Italy_NWT_prediction <- matrix(c(subset(IZSAM_Italy_SIR, Group == "pred_S")$S, 
                subset(IZSAM_Italy_SIR, Group == "pred_S")$I_R,
                subset(IZSAM_Italy_SIR, Group == "pred_I_R")$S,
                subset(IZSAM_Italy_SIR, Group == "pred_I_R")$I_R), ncol=2, byrow=TRUE)
colnames(IZSAM_Italy_NWT_prediction) <- c('S','I_R')
rownames(IZSAM_Italy_NWT_prediction) <- c('pred_S','pred_I_R')
IZSAM_Italy_NWT_prediction_summary<-metrics(IZSAM_Italy_NWT_prediction)


```


```{r LaPaz_Lazaro}

LaPaz_Lazaro_SI <- LaPaz_Lazaro %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_S" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_S_I", Group)) 


LaPaz_Lazaro_R <- LaPaz_Lazaro %>% 
  rename(Group=...1) %>% 
  filter(Group=="pred_R" | Group=="pred_I") %>%
  rowwise()%>%
  mutate(S_I = sum(S, I)) %>%
  mutate(I_R = sum(I, R)) %>%
  select(-c(I)) %>%
  adorn_totals("row") %>%
  mutate(Group = gsub("Total", "pred_I_R", Group)) 

LaPaz_Lazaro_SIR <- rbind(LaPaz_Lazaro_SI, LaPaz_Lazaro_R) %>% distinct()

subset(LaPaz_Lazaro_SIR, Group == "pred_S_I")$S_I
table(LaPaz_Lazaro_SIR$S_I)

LaPaz_Lazaro_R_prediction <- matrix(c(subset(LaPaz_Lazaro_SIR, Group == "pred_S_I")$S_I, 
                subset(LaPaz_Lazaro_SIR, Group == "pred_S_I")$R,
                subset(LaPaz_Lazaro_SIR, Group == "pred_R")$S_I,
                subset(LaPaz_Lazaro_SIR, Group == "pred_R")$R), ncol=2, byrow=TRUE)

colnames(LaPaz_Lazaro_R_prediction) <- c('S_I','R')
rownames(LaPaz_Lazaro_R_prediction) <- c('pred_S_I','pred_R')
LaPaz_Lazaro_R_prediction_summary<-metrics(LaPaz_Lazaro_R_prediction)

LaPaz_Lazaro_NWT_prediction <- matrix(c(subset(LaPaz_Lazaro_SIR, Group == "pred_S")$S, 
                subset(LaPaz_Lazaro_SIR, Group == "pred_S")$I_R,
                subset(LaPaz_Lazaro_SIR, Group == "pred_I_R")$S,
                subset(LaPaz_Lazaro_SIR, Group == "pred_I_R")$I_R), ncol=2, byrow=TRUE)
colnames(LaPaz_Lazaro_NWT_prediction) <- c('S','I_R')
rownames(LaPaz_Lazaro_NWT_prediction) <- c('pred_S','pred_I_R')
LaPaz_Lazaro_NWT_prediction_summary<-metrics(LaPaz_Lazaro_NWT_prediction)
```



# Combining validation sets
```{r combine}
validation_summary <- rbind(EUSCAPE_EURECA_R_prediction_summary$summary,
                            EUSCAPE_EURECA_NWT_prediction_summary$summary,
                            KayamaJapan_R_prediction_summary$summary, 
                            KayamaJapan_NWT_prediction_summary$summary, 
                            IndiaGHRU_R_prediction_summary$summary,
                            IndiaGHRU_NWT_prediction_summary$summary,
                            AGAR_R_prediction_summary$summary, 
                            AGAR_NWT_prediction_summary$summary,
                            Oxfordshire_Kpn_R_prediction_summary$summary, 
                            Oxfordshire_Kpn_NWT_prediction_summary$summary, 
                            IZSAM_Italy_R_prediction_summary$summary, 
                            IZSAM_Italy_NWT_prediction_summary$summary, 
                            MBIRA_Kpn_R_prediction_summary$summary,
                            MBIRA_Kpn_NWT_prediction_summary$summary, 
                            HowdenGorrie_R_prediction_summary$summary, 
                            HowdenGorrie_NWT_prediction_summary$summary,
                            Milan_R_prediction_summary$summary, 
                            Milan_NWT_prediction_summary$summary,
                            HRYC_Spain_R_prediction_summary$summary,
                            HRYC_Spain_NWT_prediction_summary$summary,
                            LaPaz_Lazaro_R_prediction_summary$summary,
                            LaPaz_Lazaro_NWT_prediction_summary$summary,
                            MBIRA_Kvv_R_prediction_summary$summary,
                            MBIRA_Kvv_NWT_prediction_summary$summary,
                            Oxfordshire_Kvv_R_prediction_summary$summary, 
                            Oxfordshire_Kvv_NWT_prediction_summary$summary, 
                            NeumannGermany_R_prediction_summary$summary,
                            NeumannGermany_NWT_prediction_summary$summary,
                            FeaseyMalawi_R_prediction_summary$summary, 
                            FeaseyMalawi_NWT_prediction_summary$summary,
                            EgliSwitzerland_R_prediction_summary$summary,
                            EgliSwitzerland_NWT_prediction_summary$summary,
                            HailuEthiopia_R_prediction_summary$summary, 
                            HailuEthiopia_NWT_prediction_summary$summary, 
                            Whitelaw_CHAMPS_R_prediction_summary$summary, 
                            Whitelaw_CHAMPS_NWT_prediction_summary$summary)


validation_summary_table <- as_tibble(validation_summary) %>%
  mutate(Prediction=c("R", "NWT","R", "NWT","R", "NWT","R", "NWT","R", "NWT", "R", "NWT", "R", "NWT","R", "NWT","R", "NWT","R", "NWT","R", "NWT","R", "NWT","R", "NWT","R", "NWT","R", "NWT","R", "NWT","R", "NWT","R", "NWT"))%>%
  mutate(Dataset=c("EUSCAPE & EURECA", "EUSCAPE & EURECA","JARBS-GNR", "JARBS-GNR", "India GHRU", "India GHRU", "AGAR GnSOP", "AGAR GnSOP","Oxfordshire","Oxfordshire","IZSAM","IZSAM", "MBIRA", "MBIRA", "Controlling Superbugs study & Victorian CPE program", "Controlling Superbugs study & Victorian CPE program",  "IRCCS Ospedale San Raffaele", "IRCCS Ospedale San Raffaele",  "HURYC & CIBERINFEC", "HURYC & CIBERINFEC", "HULP", "HULP", "MBIRA*", "MBIRA*","Oxfordshire*","Oxfordshire*", "SCHARKI", "SCHARKI", "Queen Elizabeth Central Hospital", "Queen Elizabeth Central Hospital","University of Zurich", "University of Zurich", "Addis Ababa University*", "Addis Ababa University*", "CHAMPS", "CHAMPS")) %>%
    mutate(Country=c("Various European countries", "Various European countries","Japan", "Japan", "India", "India", "Australia", "Australia","United Kingdom","United Kingdom","Italy","Italy","Tanzania, Ethiopia, Malawi, Zambia, Ghana, Nigeria, South Africa", "Tanzania, Ethiopia, Malawi, Zambia, Ghana, Nigeria, South Africa", "Australia", "Australia",  "Italy", "Italy",  "Spain, Portugal", "Spain, Portugal","Spain", "Spain", "Ethiopia, South Africa, Tanzania", "Ethiopia, South Africa, Tanzania","United Kingdom", "United Kingdom", "Germany", "Germany", "Malawi", "Malawi","Switzerland", "Switzerland", "Ethiopia", "Ethiopia", "South Africa", "South Africa")) %>%
    rename(Sensitivity=sens, Specificity=spec, `ME`=me, `VME`=vme, `Categorical agreement`=cat, `%R`=perc_R, N=n) %>%
  mutate(Sensitivity=paste0(round(as.numeric(Sensitivity)*100,2),"%")) %>%
  mutate(Specificity=paste0(round(as.numeric(Specificity)*100,2),"%")) %>%
  mutate(ME=paste0(round(as.numeric(ME)*100,2),"%")) %>%
  mutate(VME=paste0(round(as.numeric(VME)*100,2),"%")) %>%
  mutate(`Categorical agreement`=paste0(round(as.numeric(`Categorical agreement`)*100,2),"%")) %>% 
  mutate(`%R`=paste0(round(as.numeric(`%R`)*100,2),"%")) %>%
  select(Prediction, Dataset, Country, `Categorical agreement`, Sensitivity, Specificity, ME, VME, `%R` ,N)

write_csv(validation_summary_table, "../tables/Table3_extValidation_evalMetrics.csv", na="-")
 
```

# Figure 7 - external validation
```{r}
HowdenGorrie_MIC <- readPNG("HowdenGorrie_ValidationOutput/MIC_PredRIS.png", native=TRUE)
MBIRA_MIC_Kpn <- readPNG("MBIRA_ValidationOutput/MIC_PredRIS_Kpn.png", native=TRUE)
MBIRA_MIC_Kvv <- readPNG("MBIRA_ValidationOutput/MIC_PredRIS_Kvv.png", native=TRUE)
AGAR_MIC <- readPNG("AGAR_ValidationOutput/MIC_PredRIS.png", native=TRUE)
Milan_MIC <- readPNG("MilanSanRafaelle_ValidationOutput/MIC_PredRIS.png", native=TRUE)
HailuEthiopia_DD <- readPNG("HailuEthiopia_ValidationOutput/DD_PredRIS.png", native=TRUE)
KayamaJapan_MIC <- readPNG("KayamaJapan_ValidationOutput/MIC_PredRIS.png", native=TRUE)
FeaseyMalawi_DD <- readPNG("FeaseyMalawi_ValidationOutput/DD_PredRIS.png", native=TRUE)
EUSCAPE_EURECA_MIC <- readPNG("EURECA_EUSCAPE_ValidationOutput/MIC_PredRIS.png", native=TRUE)


EgliSwitzerland_DD <- readPNG("EgliSwitzerland_2025_ValidationOutput/DD_PredRIS.png", native=TRUE)
HRYC_Spain_MIC <- readPNG("HRYC_Spain_ValidationOutput/MIC_PredRIS.png", native=TRUE)
IndiaGHRU_MIC <- readPNG("IndiaGHRU_2025_ValidationOutput/MIC_PredRIS.png", native=TRUE)
NeumannGermany_MIC <- readPNG("NeumannGermany_ValidationOutput/MIC_PredRIS.png", native=TRUE)

Whitelaw_CHAMPS_DD <- readPNG("Whitelaw_Stellenbosch_ValidationOutput/DD_PredRIS.png", native=TRUE)

Oxfordshire_Kpn_MIC <- readPNG("Oxfordshire_ValidationOutput/MIC_PredRIS_Kpn.png", native=TRUE)
Oxfordshire_Kvv_MIC <- readPNG("Oxfordshire_ValidationOutput/MIC_PredRIS_Kvv.png", native=TRUE)
IZSAM_Italy_MIC <- readPNG("IZSAM_Italy_ValidationOutput/MIC_PredRIS.png", native=TRUE)
LaPaz_Lazaro_MIC <- readPNG("IZSAM_Italy_ValidationOutput/MIC_PredRIS.png", native=TRUE)

patch <- (wrap_elements(EUSCAPE_EURECA_MIC) +
            ggtitle("A) EUSCAPE & EURECA MIC (n=2133)")  +
            wrap_elements(KayamaJapan_MIC) +
            ggtitle("B) JARBS-GNR Japan MIC (n=834)")+
            wrap_elements(IndiaGHRU_MIC) +
            ggtitle("C) India GHRU MIC (n=536)")+
            wrap_elements(AGAR_MIC) + 
            ggtitle("D) AGAR GnSOP MIC (n=485)") +
            wrap_elements(Oxfordshire_Kpn_MIC) + 
            ggtitle("E) Oxfordshire MIC (n=295)") + 
            wrap_elements(IZSAM_Italy_MIC) +
            ggtitle("F) IZSAM MIC (n=263)")+            
            wrap_elements(MBIRA_MIC_Kpn) + 
            ggtitle("G) MBIRA MIC (n=263)")+     
            wrap_elements(HowdenGorrie_MIC) +
            ggtitle("H) Controlling Superbugs study & \nVictorian CPE program MIC (n=212)") +
            wrap_elements(Milan_MIC) +
            ggtitle("I) IRCCS Ospedale San Raffaele MIC (n=198)")+
            wrap_elements(HRYC_Spain_MIC) +
            ggtitle("J) HURYC & CIBERINFEC MIC (n=173)")+
            wrap_elements(LaPaz_Lazaro_MIC) +
            ggtitle("K) HULP MIC (n=148)")+
            wrap_elements(MBIRA_MIC_Kvv) + 
            ggtitle("L) MBIRA* MIC (n=92)")+
            wrap_elements(Oxfordshire_Kvv_MIC) +
            ggtitle("M) Oxfordshire* MIC (n=66)")+
            wrap_elements(NeumannGermany_MIC) +
            ggtitle("N) SCHARKI MIC (n=56)")+  
            wrap_elements(FeaseyMalawi_DD) +
            ggtitle("O) Queen Elizabeth Central Hospital \n(Malawi) DD (n=737)") +
            wrap_elements(EgliSwitzerland_DD) +
            ggtitle("P) University of Zurich DD (n=72)")+
            wrap_elements(HailuEthiopia_DD) +
            ggtitle("Q) Addis Ababa University* \n(Ethiopia) DD (n=70)")+
            wrap_elements(Whitelaw_CHAMPS_DD) +
            ggtitle("R) CHAMPS DD (n=40)")
          )+
  plot_layout(ncol = 3)

ggsave(height=13, width=13, file="../figs/Fig7_extValidation.png")
ggsave(height=13, width=13, file="../figs/Fig7_extValidation.pdf")

```




# Figure S11 - external validation (supplementary - distribution vs. genotype profile and phenotype vs. genotype profile)
```{r}
HowdenGorrie_dist <- readPNG("HowdenGorrie_ValidationOutput/MIC_PredGroup.png", native=TRUE)
HowdenGorrie_profile <- readPNG("HowdenGorrie_ValidationOutput/StackedBar_PredGroup_SIR.png", native=TRUE)

MBIRA_Kpn_dist <- readPNG("MBIRA_ValidationOutput/MIC_PredGroup_Kpn.png", native=TRUE)
MBIRA_Kpn_profile <- readPNG("MBIRA_ValidationOutput/StackedBar_PredGroup_SIR_Kpn.png", native=TRUE)

MBIRA_Kvv_dist <- readPNG("MBIRA_ValidationOutput/MIC_PredGroup_Kvv.png", native=TRUE)
MBIRA_Kvv_profile <- readPNG("MBIRA_ValidationOutput/StackedBar_PredGroup_SIR_Kvv.png", native=TRUE)

AGAR_dist <- readPNG("AGAR_ValidationOutput/MIC_PredGroup.png", native=TRUE)
AGAR_profile <- readPNG("AGAR_ValidationOutput/StackedBar_PredGroup_SIR.png", native=TRUE)

Milan_dist <- readPNG("MilanSanRafaelle_ValidationOutput/MIC_PredGroup.png", native=TRUE)
Milan_profile <- readPNG("MilanSanRafaelle_ValidationOutput/StackedBar_PredGroup_SIR.png", native=TRUE)

Hailu_dist <- readPNG("HailuEthiopia_ValidationOutput/DD_PredGroup.png", native=TRUE)
Hailu_profile <- readPNG("HailuEthiopia_ValidationOutput/StackedBar_PredGroup_SIR.png", native=TRUE)

Kayama_dist <- readPNG("KayamaJapan_ValidationOutput/MIC_PredGroup.png", native=TRUE)
Kayama_profile <- readPNG("KayamaJapan_ValidationOutput/StackedBar_PredGroup_SIR.png", native=TRUE)

Feasey_dist <- readPNG("FeaseyMalawi_ValidationOutput/DD_PredGroup.png", native=TRUE)
Feasey_profile <- readPNG("FeaseyMalawi_ValidationOutput/StackedBar_PredGroup_SIR.png", native=TRUE)
         
EUSCAPE_EURECA_dist <- readPNG("EURECA_EUSCAPE_ValidationOutput/MIC_PredGroup.png", native=TRUE)
EUSCAPE_EURECA_profile <- readPNG("EURECA_EUSCAPE_ValidationOutput/StackedBar_PredGroup_SIR.png", native=TRUE)     

EgliSwitzerland_dist <- readPNG("EgliSwitzerland_2025_ValidationOutput/DD_PredGroup.png", native=TRUE)
EgliSwitzerland_profile <- readPNG("EgliSwitzerland_2025_ValidationOutput/StackedBar_PredGroup_SIR.png", native=TRUE)           

HRYC_Spain_dist <- readPNG("HRYC_Spain_ValidationOutput/MIC_PredGroup.png", native=TRUE)
HRYC_Spain_profile <- readPNG("HRYC_Spain_ValidationOutput/StackedBar_PredGroup_SIR.png", native=TRUE)           
IndiaGHRU_dist <- readPNG("IndiaGHRU_2025_ValidationOutput/MIC_PredGroup.png", native=TRUE)
IndiaGHRU_profile <- readPNG("IndiaGHRU_2025_ValidationOutput/StackedBar_PredGroup_SIR.png", native=TRUE)           
NeumannGermany_dist <- readPNG("NeumannGermany_ValidationOutput/MIC_PredGroup.png", native=TRUE)
NeumannGermany_profile <- readPNG("NeumannGermany_ValidationOutput/StackedBar_PredGroup_SIR.png", native=TRUE)           

WhitelawCHAMPS_dist <- readPNG("Whitelaw_Stellenbosch_ValidationOutput/DD_PredGroup.png", native=TRUE)
WhitelawCHAMPS_profile <- readPNG("Whitelaw_Stellenbosch_ValidationOutput/StackedBar_PredGroup_SIR_DD.png", native=TRUE)    

Oxfordshire_Kpn_dist <- readPNG("Oxfordshire_ValidationOutput/MIC_PredGroup_Kpn.png", native=TRUE)
Oxfordshire_Kpn_profile <- readPNG("Oxfordshire_ValidationOutput/StackedBar_PredGroup_SIR_Kpn.png", native=TRUE)    

Oxfordshire_Kvv_dist <- readPNG("Oxfordshire_ValidationOutput/MIC_PredGroup_Kvv.png", native=TRUE)
Oxfordshire_Kvv_profile <- readPNG("Oxfordshire_ValidationOutput/StackedBar_PredGroup_SIR_Kvv.png", native=TRUE)    

IZSAM_Italy_dist <- readPNG("IZSAM_Italy_ValidationOutput/MIC_PredGroup.png", native=TRUE)
IZSAM_Italy_profile <- readPNG("IZSAM_Italy_ValidationOutput/StackedBar_PredGroup_SIR.png", native=TRUE)    
LaPaz_Lazaro_dist <- readPNG("LaPaz_Lazaro_ValidationOutput/MIC_PredGroup.png", native=TRUE)
LaPaz_Lazaro_profile <- readPNG("LaPaz_Lazaro_ValidationOutput/StackedBar_PredGroup_SIR.png", native=TRUE)    

  (wrap_elements(EUSCAPE_EURECA_dist) +ggtitle("A) EURECA & EUSCAPE (n=2133) - MIC distribution vs.\n genotype profile") + wrap_elements(EUSCAPE_EURECA_profile) + ggtitle("B) EURECA & EUSCAPE (n=2133) - observed phenotype vs.\n genotype profile"))/
  
(wrap_elements(Kayama_dist) +ggtitle("C) JARBS-GNR Japan (n=834) - MIC distribution vs.\n genotype profile") + wrap_elements(Kayama_profile) + ggtitle("D) JARBS-GNR Japan (n=834) - observed phenotype vs.\n genotype profile")) /

  (wrap_elements(IndiaGHRU_dist) +ggtitle("E) India GHRU (n=536) - MIC distribution vs.\n genotype profile") + wrap_elements(IndiaGHRU_profile) + ggtitle("F) India GHRU (n=536) - observed phenotype vs.\n genotype profile")) /
  (wrap_elements(AGAR_dist) +ggtitle("G) AGAR GnSOP (n=485) - MIC distribution vs.\n genotype profile") + wrap_elements(AGAR_profile) + ggtitle("H) AGAR GnSOP (n=485) - observed phenotype vs.\n genotype profile")) 

ggsave(height=13, width=11, file="../figs/FigS11_extValidation_genoprofiles_1.png")
ggsave(height=13, width=11, file="../figs/FigS11_extValidation_genoprofiles_1.pdf")


(wrap_elements(Oxfordshire_Kpn_dist) +ggtitle("I) Oxfordshire (n=295) - MIC distribution vs.\n genotype profile") + wrap_elements(Oxfordshire_Kpn_profile) + ggtitle("J) Oxfordshire (n=295) - observed phenotype vs.\n genotype profile")) /
  
  (wrap_elements(IZSAM_Italy_dist) +ggtitle("K) IZSAM (n=283) - MIC distribution vs.\n genotype profile") + wrap_elements(IZSAM_Italy_profile) + ggtitle("L) IZSAM (n=283) - observed phenotype vs.\n genotype profile")) /
  

(wrap_elements(MBIRA_Kpn_dist) +ggtitle("M) MBIRA (n=263) - MIC distribution vs.\n genotype profile") + wrap_elements(MBIRA_Kpn_profile) + ggtitle("N) MBIRA (n=263) - observed phenotype vs.\n genotype profile")) /
  
(wrap_elements(HowdenGorrie_dist) +ggtitle("O) Controlling Superbugs study & \nVictorian CPE program (n=212) - MIC distribution vs.\n genotype profile") + wrap_elements(HowdenGorrie_profile) + ggtitle("P) Controlling Superbugs study & \nVictorian CPE program (n=212) - observed phenotype vs.\n genotype profile")) 
  


ggsave(height=13, width=10, file="../figs/FigS11_extValidation_genoprofiles_2.png")
ggsave(height=13, width=10, file="../figs/FigS11_extValidation_genoprofiles_2.pdf")

(wrap_elements(Milan_dist) +ggtitle("Q) IRCCS Ospedale San Raffaele (n=198) - MIC distribution vs.\n genotype profile") + wrap_elements(Milan_profile) + ggtitle("R) IRCCS Ospedale San Raffaele (n=198) \n - observed phenotype vs. genotype profile"))/

  
  (wrap_elements(HRYC_Spain_dist) +ggtitle("S) HURYC & CIBERINFEC (n=173) - MIC distribution vs.\n genotype profile") + wrap_elements(HRYC_Spain_profile) + ggtitle("T) HURYC & CIBERINFEC (n=173) \n - observed phenotype vs. genotype profile")) /
  

    (wrap_elements(LaPaz_Lazaro_dist) +ggtitle("U) HULP (n=148) - MIC distribution vs.\n genotype profile") + wrap_elements(LaPaz_Lazaro_profile) + ggtitle("V) HULP (n=148) \n - observed phenotype vs. genotype profile")) /

(wrap_elements(MBIRA_Kvv_dist) +ggtitle("W) MBIRA* (n=92) - MIC distribution vs.\n genotype profile") + wrap_elements(MBIRA_Kvv_profile) + ggtitle("X) MBIRA* (n=92) - observed phenotype vs.\n genotype profile")) 

ggsave(height=13, width=10, file="../figs/FigS11_extValidation_genoprofiles_3.png")
ggsave(height=13, width=10, file="../figs/FigS11_extValidation_genoprofiles_3.pdf")


(wrap_elements(Oxfordshire_Kvv_dist) +ggtitle("Y) Oxfordshire* (n=66) - MIC distribution vs.\n genotype profile") + wrap_elements(Oxfordshire_Kvv_profile) + ggtitle("Z) Oxfordshire* (n=66) - observed phenotype vs.\n genotype profile")) /

(wrap_elements(NeumannGermany_dist) +ggtitle("AA) SCHARKI (n=56) - MIC distribution vs.\n genotype profile") + wrap_elements(NeumannGermany_profile) + ggtitle("BB) SCHARKI (n=56) - observed phenotype vs.\n genotype profile")) /

(wrap_elements(Feasey_dist) +ggtitle("CC) Queen Elizabeth Central Hospital Malawi (n=737) \n - DD distribution vs. genotype profile") + wrap_elements(Feasey_profile) + ggtitle("DD) Queen Elizabeth Central Hospital Malawi (n=737) \n - observed phenotype vs. genotype profile")) /
  
  (wrap_elements(EgliSwitzerland_dist) +ggtitle("EE) University of Zurich (n=72) - DD distribution vs.\n genotype profile") + wrap_elements(EgliSwitzerland_profile) + ggtitle("FF) University of Zurich (n=72) - observed phenotype vs.\n genotype profile")) 

ggsave(height=13, width=10, file="../figs/FigS11_extValidation_genoprofiles_4.png")
ggsave(height=13, width=10, file="../figs/FigS11_extValidation_genoprofiles_4.pdf")

(wrap_elements(Hailu_dist) +ggtitle("GG) Addis Ababa University* (n=70) - DD distribution vs.\n genotype profile") + wrap_elements(Hailu_profile) + ggtitle("HH) Addis Ababa University* (n=70) - observed phenotype vs.\n genotype profile")) /

(wrap_elements(WhitelawCHAMPS_dist) +ggtitle("II) CHAMPS (n=40) - DD distribution vs.\n genotype profile") + wrap_elements(WhitelawCHAMPS_profile) + ggtitle("JJ) CHAMPS (n=40) - observed phenotype vs.\n genotype profile")) 

ggsave(height=13, width=10, file="../figs/FigS11_extValidation_genoprofiles_5.png")
ggsave(height=13, width=10, file="../figs/FigS11_extValidation_genoprofiles_5.pdf")


```



# numbers for summary

```{r load_data_summary}

validation_phenotypes <- read_delim("../tables/TableS4_phenotype_metadata_validation.tsv")
validation_genotypes <- read_delim("../tables/TableS3_genotypes_validation.tsv")
summary <- read_delim("../tables/Table3_extValidation_evalMetrics.csv")

```

```{r summary_genotypes_phenotypes}

# Have to add EUSCAPE + SAN RAF data 
# EUSCAPE = 2133 Kpn
# IRCCS Ospedale San Raffaele = 198 Kpn 
validation_genotypes %>% count(species)

# EUSCAPE = 2133 MIC
# IRCCS Ospedale San Raffaele = 198 MIC
validation_phenotypes %>% count(Laboratory.Typing.Method)

```

```{r summary_validation}
summary[] <- lapply(summary, gsub, pattern='%', replacement='')

summary %>% group_by(Prediction) %>% 
  summarise(avg_CA = mean(as.numeric(`Categorical agreement`), na.rm = T)) 
summary %>% group_by(Prediction) %>%
  summarise(min_CA = min(as.numeric(`Categorical agreement`), na.rm = T)) 
  summary %>% group_by(Prediction) %>%
  summarise(max_CA = max(as.numeric(`Categorical agreement`), na.rm = T))
  
summary %>% group_by(Prediction) %>% 
  summarise(avg_sens = mean(as.numeric(Sensitivity), na.rm = T))
summary %>% group_by(Prediction) %>%
  summarise(min_CA = min(as.numeric(Sensitivity), na.rm = T)) 
  summary %>% group_by(Prediction) %>%
  summarise(max_CA = max(as.numeric(Sensitivity), na.rm = T))

summary %>% group_by(Prediction) %>% 
  summarise(avg_spec = mean(as.numeric(Specificity), na.rm = T)) 
summary %>% group_by(Prediction) %>%
  summarise(min_CA = min(as.numeric(Specificity), na.rm = T)) 
  summary %>% group_by(Prediction) %>%
  summarise(max_CA = max(as.numeric(Specificity), na.rm = T))
  
  
summary %>% group_by(Prediction) %>% 
  summarise(avg_ME = mean(as.numeric(ME), na.rm = T))
summary %>% group_by(Prediction) %>%
  summarise(min_CA = min(as.numeric(ME), na.rm = T)) 
  summary %>% group_by(Prediction) %>%
  summarise(max_CA = max(as.numeric(ME), na.rm = T))
  
  
summary %>% group_by(Prediction) %>% 
  summarise(avg_VME = mean(as.numeric(VME), na.rm = T)) 
summary %>% group_by(Prediction) %>%
  summarise(min_CA = min(as.numeric(VME), na.rm = T)) 
  summary %>% group_by(Prediction) %>%
  summarise(max_CA = max(as.numeric(VME), na.rm = T))
```